#!/usr/bin/env python3
"""
Test Three Language Formula Question Generation
Telangana State Board Class 10 - All Three Languages + Core Subjects
"""

from app.db import SessionLocal
from app.teacher import generate_and_store_questions
from app.models import Assessment, User, Question
from datetime import datetime, timedelta

def test_three_language_formula():
    """
    Test generating questions for all subjects in Class 10 (Configuration A)
    """
    db = SessionLocal()

    try:
        print("=" * 80)
        print("TESTING THREE LANGUAGE FORMULA")
        print("Telangana State Board - Class 10 - Configuration A")
        print("=" * 80)

        # Get teacher
        teacher = db.query(User).filter_by(role='teacher').first()
        if not teacher:
            print("\n❌ No teacher found")
            return

        print(f"\n✅ Using teacher: {teacher.name} (ID: {teacher.id})")

        # Test cases for all 6 subjects
        test_cases = [
            {
                'subject': 'English',
                'chapter': 'A Letter to God',
                'language_position': 'FL',
                'description': '1️⃣ English (First Language)'
            },
            {
                'subject': 'Telugu',
                'chapter': 'మాతృభూమి',
                'language_position': 'SL',
                'description': '2️⃣ Telugu (Second Language)'
            },
            {
                'subject': 'Hindi',
                'chapter': 'बड़े भाई साहब',
                'language_position': 'TL',
                'description': '3️⃣ Hindi (Third Language)'
            },
            {
                'subject': 'Mathematics',
                'chapter': 'Real Numbers',
                'language_position': None,
                'description': '📐 Mathematics (Core Subject)'
            },
            {
                'subject': 'Science',
                'chapter': 'Chemical Reactions and Equations',
                'language_position': None,
                'description': '🔬 Science (Core Subject)'
            },
            {
                'subject': 'Social Studies',
                'chapter': 'The Rise of Nationalism in Europe',
                'language_position': None,
                'description': '🌍 Social Studies (Core Subject)'
            }
        ]

        for i, test in enumerate(test_cases, 1):
            print(f"\n{'=' * 80}")
            print(f"TEST {i}/6: {test['description']}")
            print(f"{'=' * 80}")

            # Create assessment
            start_time = datetime.now()
            end_time = start_time + timedelta(hours=1)

            assessment = Assessment(
                teacher_id=teacher.id,
                class_name='10',
                section='A',
                subject=test['subject'],
                chapter=test['chapter'],
                start_time=start_time,
                end_time=end_time,
                duration_minutes=60
            )

            db.add(assessment)
            db.commit()
            db.refresh(assessment)

            print(f"\nAssessment ID: {assessment.id}")
            print(f"Subject: {test['subject']}")
            print(f"Chapter: {test['chapter']}")
            if test['language_position']:
                print(f"Language Level: {test['language_position']}")

            # Generate questions
            print(f"\nGenerating questions...")
            generate_and_store_questions(
                assessment_id=assessment.id,
                class_name='10',
                subject=test['subject'],
                chapter=test['chapter'],
                board_code='TSBSE',
                medium='English',
                language_position=test['language_position']
            )

            # Verify
            questions = db.query(Question).filter_by(assessment_id=assessment.id).all()

            if questions:
                print(f"\n✅ {len(questions)} questions generated")
                print(f"\nSample Question:")
                q = questions[0]
                print(f"Q: {q.question}")
                for key, value in q.options.items():
                    marker = "✓" if key == q.correct_answer else " "
                    print(f"  [{marker}] {key}: {value}")
            else:
                print(f"\n⚠️ No questions generated")

        print(f"\n{'=' * 80}")
        print("FINAL SUMMARY")
        print(f"{'=' * 80}")

        # Count questions by subject
        print(f"\nQuestions Generated by Subject:")
        for test in test_cases:
            assessments = db.query(Assessment).filter_by(
                subject=test['subject'],
                class_name='10'
            ).all()

            total_questions = 0
            for a in assessments:
                total_questions += db.query(Question).filter_by(assessment_id=a.id).count()

            lang_info = f" ({test['language_position']})" if test['language_position'] else ""
            print(f"  {test['subject']}{lang_info}: {total_questions} questions")

        print(f"\n{'=' * 80}")
        print("✅ THREE LANGUAGE FORMULA TESTING COMPLETE!")
        print(f"{'=' * 80}")

    except Exception as e:
        print(f"\n❌ ERROR: {e}")
        import traceback
        traceback.print_exc()
        db.rollback()

    finally:
        db.close()


if __name__ == "__main__":
    test_three_language_formula()
